title: Paul Hongsuck Seo
logo: /assets/img/logo.png
description: AAA
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/citations?user=Tp7U8_UAAAAJ&hl=en
