title: Paul Hongsuck Seo
position: Research Scientist, Google
email: phseo
logo: /assets/img/profile.png
google_analytics:
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/citations?user=Tp7U8_UAAAAJ&hl=en

publications:
  - title: MarioQA: Answering Questions by Watching Gameplay Videos
    url: http://openaccess.thecvf.com/content_iccv_2017/html/Mun_MarioQA_Answering_Questions_ICCV_2017_paper.html
    authors: *Jonghwan Mun, *Paul Hongsuck Seo, Ilchae Jung, Bohyung Han (* equal contribution)
    conf: ICCV 2017
    project_page: http://cvlab.postech.ac.kr/research/MarioQA/
  - title: Image Question Answering using Convolutional Neural Network with Dynamic Parameter Prediction
    url: http://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Noh_Image_Question_Answering_CVPR_2016_paper.pdf
    authors: Hyeonwoo Noh, Paul Hongsuck Seo, Bohyung Han
    conf: CVPR 2016
    oral: true
    project_page: http://cvlab.postech.ac.kr/research/dppnet/
  - title: A Corpus for a Multimodal Dialog System for Presentation Controls
    url: #
    authors: Paul Hongsuck Seo, Gary Geunbae Lee
    conf: Proceedings of the International Workshop Series on Multimodal Corpora (MMC 2016)
  - title: Conversational Knowledge Teaching Agent that Uses a Knowledge Base
    url: http://www.aclweb.org/anthology/W/W15/W15-4618.pdf
    authors: Kyusong Lee, Paul Hongsuck Seo, Junhwi Choi, Sangjun Koo, Gary Geunbae Lee
    conf: SIGDIAL 2015
    
  - title: Grammatical Error Correction based on Learner Comprehension Model in Oral Conversation
    url: http://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7078588
    authors: Kyusong Lee, Seonghan Ryu, Paul Hongsuck Seo, Seokhwan Kim, Gary Geunbae Lee
    conf: Proceedings of the IEEE Workshop on Spoken Language Technology (SLT 2014)
  - title: Generating Grammar Questions using Corpus Data in L2 Learning
    url: http://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6424265&tag=1
    authors: Kyusong Lee, Soo-ok Kweon, Hongsuck Seo, Gary Geunbae Lee
    conf: Proceedings of the IEEE Workshop on Spoken Language Technology (SLT 2012)
  - title: A Meta-Learning Approach to Grammatical Error Correction
    url: https://aclanthology.coli.uni-saarland.de/papers/P12-2064/p12-2064
    authors: Hongsuck Seo, Jonghoon Lee, Seokhwan Kim, Kyusong Lee, Sechun Kang, Gary Geunbae Lee
    conf: ACL 2012
  - title: Grammatical Error Annotation for Korean Learners of Spoken English
    url: http://www.lrec-conf.org/proceedings/lrec2012/pdf/168_Paper.pdf
    authors: Hongsuck Seo, Kyusong Lee, Gary Geunbae Lee, Soo-ok Kweon
    conf: LREC 2012
