title: Paul Hongsuck Seo
description: Assistant Professor @ Korea University
position: |
  Assistant Professor, 
  Korea University
email: phseo
logo: /assets/img/profile.png
google_analytics:
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/citations?user=Tp7U8_UAAAAJ&hl=en

publications:
  - title: "Pseudo-RIS: Distinctive Pseudo-supervision Generation for Referring Image Segmentation"
    authors: "Seonghoon Yu, +Paul Hongsuck Seo, +Jeany Son (+ corresponding authors)"
    url: #
    conf: ECCV 2024
  - title: "CAT-Seg: Cost Aggregation for Open-vocabulary Semantic Segmentation"
    authors: "*Seokju Cho, *Heeseong Shin, Sunghwan Hong, Anurag Arnab, +Paul Hongsuck Seo, +Seungryong Kim (+ corresponding authors)"
    conf: CVPR 2024
    url: https://arxiv.org/abs/2303.11797
    highlight: 1
  - title: "Learning Correlation Structures for Vision Transformers"
    url: #
    authors: Manjin Kim, +Paul Hongsuck Seo, Cordelia Schmid, +Minsu Cho (+ corresponding authors)
    conf: CVPR 2024
  - title: "AVFormer: Injecting Vision into Frozen Speech Models for Zero-Shot AV-ASR"
    url: #
    authors: Paul Hongsuck Seo, Arsha Nagrani, Cordelia Schmid
    conf: CVPR 2023
  - title: "IFSeg: Image-free Semantic Segmentation via Vision-Language Model"
    url: #
    authors: Sukmin Yun, Seong Hyeon Park, Paul Hongsuck Seo, Jinwoo Shin
    conf: CVPR 2023
  - title: "Vid2Seq: Large-Scale Pretraining of a Visual Language Model for Dense Video Captioning"
    url: #
    authors: Antoine Yang, Arsha Nagrani, Paul Hongsuck Seo, Antoine Miech, Jordi Pont-Tuset, Ivan Laptev, Josef Sivic, Cordelia Schmid
    conf: CVPR 2023
  - title: "Zero-shot Referring Image Segmentation with Global-Local Context Features"
    url: #
    authors: Seonghoon Yu, Paul Hongsuck Seo, Jeany Son
    conf: CVPR 2023
  - title: "Learning Audio-Video Modalities from Image Captions"
    url: https://arxiv.org/abs/2204.00679
    authors: Arsha Nagrani, Paul Hongsuck Seo, Bryan Seybold, Anja Hauth, Santiago Manen, Chen Sun, Cordelia Schmid
    conf: ECCV 2022
  - title: "AVATAR: Unconstrained Audiovisual Speech Recognition"
    url: https://arxiv.org/abs/2206.07684
    authors: "*Valentin Gabeur, *Paul Hongsuck Seo, *Arsha Nagrani, Chen Sun, Karteek Alahari, Cordelia Schmid (* equal contribution)"
    conf: Interspeech 2022
    oral: true
  - title: "End-to-end Generative Pretraining for Multimodal Video Captioning"
    url: https://arxiv.org/abs/2201.08264
    authors: Paul Hongsuck Seo, Arsha Nagrani, Anurag Arnab, Cordelia Schmid
    conf: CVPR 2022
  - title: "Look Before you Speak: Visually Contextualized Utterances"
    url: https://arxiv.org/abs/2012.05710
    authors: Paul Hongsuck Seo, Arsha Nagrani, Cordelia Schmid
    conf: CVPR 2021
  - title: Reinforcing an Image Caption Generator by Human Feedback
    url: https://arxiv.org/pdf/1911.09753.pdf
    authors: Paul Hongsuck Seo, Piyush Sharma, Tomer Levinboim, Bohyung Han, Radu Soricut
    conf: AAAI 2020
    oral: true
  - title: Combinatorial Inference against Label Noise
    url: https://papers.nips.cc/paper/8401-combinatorial-inference-against-label-noise.pdf
    authors: Paul Hongsuck Seo, Geeho Kim, Bohyung Han
    conf: NeurIPS 2019
  - title: Regularizing Neural Networks via Stochastic Branch Layers
    url: https://arxiv.org/abs/1910.01467
    authors: "*Wonpyo Park, *Paul Hongsuck Seo, Bohyung Han, Minsu Cho (* equal contribution)"
    conf: ACML 2019
    oral: true
  - title: Learning for Single-Shot Confidence Calibration in Deep Neural Networks through Stochastic Inferences
    url: https://arxiv.org/abs/1809.10877
    authors: "*Seonguk Seo, *Paul Hongsuck Seo, Bohyung Han (* equal contribution)"
    conf: CVPR 2019
  - title: "CPlaNet: Enhancing Image Geolocalization by Combinatorial Partitioning of Maps"
    url: https://arxiv.org/abs/1808.02130
    authors: Paul Hongsuck Seo, Tobias Weyand, Jack Sim, Bohyung Han
    conf: ECCV 2018
  - title: Attentive Semantic Alignment with Offset-Aware Correlation Kernels
    url: https://arxiv.org/abs/1808.02128
    authors: Paul Hongsuck Seo, Jongmin Lee, Deunsol Jung, Bohyung Han, Minsu Cho
    conf: ECCV 2018
    project_page: http://cvlab.postech.ac.kr/research/A2Net/
  - title: Progressive Attention Networks for Visual Attribute Prediction
    url: https://arxiv.org/abs/1606.02393
    authors: Paul Hongsuck Seo, Zhe Lin, Scott Cohen, Xiaohui Shen, Bohyung Han
    conf: BMVC 2018
  - title: Visual Reference Resolution using Attention Memory for Visual Dialog
    url: https://papers.nips.cc/paper/6962-visual-reference-resolution-using-attention-memory-for-visual-dialog
    authors: Paul Hongsuck Seo, Andreas Lehrmann, Bohyung Han, Leonid Sigal
    conf: NIPS 2017
    project_page: http://cvlab.postech.ac.kr/research/attmem/
  - title: "MarioQA: Answering Questions by Watching Gameplay Videos"
    url: http://openaccess.thecvf.com/content_iccv_2017/html/Mun_MarioQA_Answering_Questions_ICCV_2017_paper.html
    authors: "*Jonghwan Mun, *Paul Hongsuck Seo, Ilchae Jung, Bohyung Han (* equal contribution)"
    conf: ICCV 2017
    project_page: http://cvlab.postech.ac.kr/research/MarioQA/
  - title: Image Question Answering using Convolutional Neural Network with Dynamic Parameter Prediction
    url: https://www.cv-foundation.org/openaccess/content_cvpr_2016/papers/Noh_Image_Question_Answering_CVPR_2016_paper.pdf
    authors: Hyeonwoo Noh, Paul Hongsuck Seo, Bohyung Han
    conf: CVPR 2016
    oral: true
    project_page: http://cvlab.postech.ac.kr/research/dppnet/
  - title: A Corpus for a Multimodal Dialog System for Presentation Controls
    url: #
    authors: Paul Hongsuck Seo, Gary Geunbae Lee
    conf: Proceedings of the International Workshop Series on Multimodal Corpora (MMC 2016)
  - title: Conversational Knowledge Teaching Agent that Uses a Knowledge Base
    url: https://www.aclweb.org/anthology/W/W15/W15-4618.pdf
    authors: Kyusong Lee, Paul Hongsuck Seo, Junhwi Choi, Sangjun Koo, Gary Geunbae Lee
    conf: SIGDIAL 2015
  - title: Grammatical Error Correction based on Learner Comprehension Model in Oral Conversation
    url: https://ieeexplore.ieee.org/xpl/articleDetails.jsp?arnumber=7078588
    authors: Kyusong Lee, Seonghan Ryu, Paul Hongsuck Seo, Seokhwan Kim, Gary Geunbae Lee
    conf: Proceedings of the IEEE Workshop on Spoken Language Technology (SLT 2014)
  - title: Generating Grammar Questions using Corpus Data in L2 Learning
    url: https://ieeexplore.ieee.org/xpls/abs_all.jsp?arnumber=6424265&tag=1
    authors: Kyusong Lee, Soo-ok Kweon, Hongsuck Seo, Gary Geunbae Lee
    conf: Proceedings of the IEEE Workshop on Spoken Language Technology (SLT 2012)
  - title: A Meta-Learning Approach to Grammatical Error Correction
    url: https://aclanthology.coli.uni-saarland.de/papers/P12-2064/p12-2064
    authors: Hongsuck Seo, Jonghoon Lee, Seokhwan Kim, Kyusong Lee, Sechun Kang, Gary Geunbae Lee
    conf: ACL 2012
  - title: Grammatical Error Annotation for Korean Learners of Spoken English
    url: https://www.lrec-conf.org/proceedings/lrec2012/pdf/168_Paper.pdf
    authors: Hongsuck Seo, Kyusong Lee, Gary Geunbae Lee, Soo-ok Kweon
    conf: LREC 2012
