title: Paul Hongsuck Seo
position: Research Scientist, Google
email: phseo
logo: /assets/img/profile.png
google_analytics:
theme: jekyll-theme-minimal
google_scholar: https://scholar.google.com/citations?user=Tp7U8_UAAAAJ&hl=en

publications:
  - title: abc
    authors: test
    conf: ccvvas
  - title: abc1
    authors: test1
    conf: ccvvas1
  - title: abc2
    authors: test2
    conf: ccvvas2
  - title: abc3
    authors: test3
    conf: ccvvas3
